export const notiflixSettings = {
  width: '530px',
  position: 'center-top',
  distance: '89px',
  opacity: 1,
  borderRadius: '0',
  rtl: false,
  timeout: 4000,
  messageMaxLength: 110,
  backOverlay: false,
  backOverlayColor: 'rgba(0,0,0,0.5)',
  plainText: true,
  showOnlyTheLastOne: true,
  clickToClose: false,
  pauseOnHover: true,

  ID: 'NotiflixNotify',
  className: 'notiflix-notify',
  zindex: 4001,
  fontFamily: 'Quicksand',
  fontSize: '24px',
  cssAnimation: true,
  cssAnimationDuration: 400,
  cssAnimationStyle: 'fade',
  closeButton: false,
  useIcon: false,
  useFontAwesome: false,
  fontAwesomeIconStyle: 'basic',
  fontAwesomeIconSize: '34px',

  info: {
    background: '#ffe194',
    textColor: '#4c4c6d',
    childClassName: 'notiflix-notify-info',
    notiflixIconColor: '#4c4c6d',
    fontAwesomeClassName: 'fas fa-info-circle',
    fontAwesomeIconColor: 'rgba(38,192,211,0.2)',
    backOverlayColor: 'rgba(38,192,211,0.2)',
  },
};
